### ISSUE TITLE
Feature request: Easier random words and romaji spelling

### ISSUE THREAD

**Issue by KarukSophia** [obfusk/jiten#88]
Hi, thanks for fixing the installation problem, I really enjoy this program. I mainly use the random word function, however I am still very new to learning Japanese, so it would be nice if it was possible to get easier words (more commonly used words, shorter words). It would also be nice with an option to also list the romaji spelling. The command that I am using is this one btw:

`$ jiten -v jmdict +random`

I don't know how the database that you interface with is built up, so I have no idea how hard this would be to implement. But, I think this would be a nice addition, prioritize however you want, just an idea.

**Comment by obfusk** [comment]
Glad you like it! I wish I had this dictionary when I just started learning Japanese :)

It's not really intended as a learning tool for beginners though; I suggest you use some kind of spaced repetition tool like [anki](https://en.wikipedia.org/wiki/Anki_(software)) or [kakugo](https://github.com/blastrock/kakugo#readme) for that.

I've split your requests into 2+ issues and am closing this one for now (though feel free to comment here).

I just implemented #89, which allows you to do

```bash
$ jiten -v jmdict +random --prio
```

To get "priority" (i.e. commonly used) words.
You can also use `--noun` and `--verb` to only get nouns/verbs (these options did not work w/ `+random` before).

If you want to try this out, I suggest you install the development version of `jiten` via `git` (since it might be a little while before I add enough features and/or fix enough bugs to release a new version).

I intend to improve the "priority" classification at some point (#25), which would allow more fine-grained control.

I've opened #91, but I'm not yet sure if and when I'll be implementing that.
If you come up with a good definition of "easy" words that is not covered by that or "priority", I'd be happy to consider that.

Regarding romaji output: I will look into #90 soon(ish).

**Comment by obfusk** [comment]
@KarukSophia You can now search for e.g. N5-N3 vocabulary using `--jlpt 3-5`.

At the moment this only works on `master`, but I expect to release a new version sometime soon.
